# https://docs.travis-ci.com/user/deployment/pages/
# https://docs.travis-ci.com/user/languages/python/
language: python

python:
    - "3.6"

install:
    - uname -a
    - wget https://github.com/gohugoio/hugo/releases/download/v0.54.0/hugo_0.54.0_Linux-64bit.deb
    - sudo dpkg -i hugo*.deb
    - hugo version
    - rm -rf blog
    - pwd
    - git clone https://github.com/imxood/hugo-theme-slim.git themes/slim
    - ls
    - ls themes/slim

script:
    - hugo --theme=slim -d blog
    - echo 'Hugo build done!'

after_success:
    - pwd
    - git config --global user.email "imxood@gmail.com"
    - git config --global user.name "mx"
    - git clone https://$GITHUB_TOKEN@github.com/imxood/imxood.github.io.git container
    - cp -r blog/* container
    - cd container
    - ls
    - git add .
    - git commit -m 'Travis upate blog'
    - git push -u origin master
